//
// Created by Tamás Dinh on 2019-08-09.
//

#ifndef INC_2_CPP_DATASTRUCTURE_IMPLEMENTATIONS_QUEUEEMPTY_H
#define INC_2_CPP_DATASTRUCTURE_IMPLEMENTATIONS_QUEUEEMPTY_H

class QueueEmpty {};

#endif //INC_2_CPP_DATASTRUCTURE_IMPLEMENTATIONS_QUEUEEMPTY_H
